### ISSUE TITLE
Backpacks don't render.

### ISSUE THREAD

**Issue by SkullDaisyGimp** [DreenDex/ImprovedBackpacks-Issues#1]
**Description:** My backpack doesn't render when equipped; the straps used to appear on my avatar but not the actual "pack." Now none of it appears. I'd assume that the backpack mod would be compatible with texture packs and such, though I could be in error. I use the Dokucraft Dwarven variant with a few custom textures and models, but nothing that should affect anything added by a mod.
The only other mod that I have installed that should affect my avatar in any way is Mo' Bends, which to my knowledge should only change how the character animates, not how it actually appears.

**To Reproduce:**
1. I equip the backpack to the chest slot in my inventory. No pack appears.

**Expected behavior:**
The backpack should appear on my back, as it does in the screenshots on the overview.

**Screenshots (If applicable):**
![2018-05-29_14 40 01](https://user-images.githubusercontent.com/39746150/40684518-cb3f52f2-634e-11e8-9571-4db5e24f223a.png)
![2018-05-29_14 40 08](https://user-images.githubusercontent.com/39746150/40684520-cd5285d2-634e-11e8-8f28-9602e8963f40.png)
![2018-05-29_14 40 13](https://user-images.githubusercontent.com/39746150/40684526-cf17ecb8-634e-11e8-8db9-df3fbf294fd2.png)

**Additional information:**
Minecraft version: 1.12.2
Forge version: 14.23.4.2703 (though I had the same problem with other Forge versions)
Mod version: 1.12.2-1.2.0.3

**Comment by NotASocol** [comment]
This problem causes by Mo' Bends. We simply don't modify their model to render backpack. I think, that we can not fix it. But we will try. Mo' Bends mod has a lot of issues with rendering other mod's thigs.

**Comment by NotASocol** [comment]
Sorry, but Mo' Bends are using hard override of player render. We can force render backpack, but it will be in wrong pos.
![aaa](https://user-images.githubusercontent.com/14280202/40687780-6cbb252a-63a4-11e8-9a54-7c1be6f66a83.png)

**Comment by SkullDaisyGimp** [comment]
I gotcha, that explains it. Thanks much! Strangely, I only had the straps render before I installed Mo' Bends, maybe there's another mod that's not playing nicely with this one.
