### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by voidswrath** [DreenDex/ImprovedBackpacks-Issues#14]
**Description:**
Crashed while using backpack on server

**To Reproduce:**
1. Interacting with backpack on ground.  

Crash Report: https://pastebin.com/qBQMxxxc

**Additional information:**
Minecraft version: 1.12.2
Forge version: 2816
Mod version: ImprovedBackpacks-1.12.2-1.4.0.0

**Comment by Kirin92** [comment]
Same here

**Comment by socolio** [comment]
Will be fixed in 1.5.0.0.
