### ISSUE TITLE
Server crash claiming an area with backpack in it.

### ISSUE THREAD

**Issue by TheCaptain13** [DreenDex/ImprovedBackpacks-Issues#16]
**Description:**
Tried using GriefPrevention plugin to claim an area which contained a backpack and it crashed instantly. tested it a few times and same thing.

**To Reproduce:**
1. place backpack down
2. claim area with backpack in.
3. crash

**Crash Report:**
https://pastebin.com/RYD6J9QM

**Additional information:**
Minecraft version: 1.12.2
Forge version: 1.12.2-14.23.5.2831
Mod version: 1.12.2-1.4.0.0
SpongeForge version: RC3689
GriefPrevention version: 1.12.2-4.3.0.689

**Comment by LemADEC** [comment]
Dup of  #14 which is fixed in 1.5.0.0
