### ISSUE TITLE
Game crashed after swapping item with backpack in my hot bar

### ISSUE THREAD

**Issue by quintonn** [DreenDex/ImprovedBackpacks-Issues#17]
**Description:**
I am playing Sevtech ages, and as far as I can tell, this mod is being used to add backpacks.
I opened my backpack inventory and then by accident dragged a potato to the backpack slot in my hotbar. This closed the backpack and the backpack dissapear and my right click didn't work anymore. I.E. i couldn't sleep, open chests, mine or do anything. I think the game thought i was still holding the backpack, but it wasn't there, even if i placed another item in my hotbar slot. Then after a couple of minutes the game just crashed.

Some extra info.
I'm using Twitch launcher to play Sevtech ages so it takes care of downloading all the required mods, including this one.
After the game crashed and loaded my game back up.
Now the potato was in the right slot but the backpack was still gone, i can't find it, seems it was destroyed with this action.

**To Reproduce:**
1. Place a backpack in hotbar slot 8.
2. Right-click to open backpack inventory.
3. While backpack inventory is open, drag an item from normal inventory to backpack slot in hotbar (in this case, slot 8). In my case it was a cooked potato.

**Expected behavior:**
Backpack swaps positions with item dragged from normal inventory, or nothing would be acceptable too.

**Screenshots (If applicable):**

**Additional information:**
Minecraft version:  1.12.2
Forge version: Not sure
Mod version: ImprovedBackpacks-1.12.2-1.2.0.3

**Comment by socolio** [comment]
Will be fixed in 1.5.0.0.
