### ISSUE TITLE
Crash while picking up Placed Backpack

### ISSUE THREAD

**Issue by Lopi13** [DreenDex/ImprovedBackpacks-Issues#21]
**Description:**
While i Pickedup the Backpack my game crashed
**To Reproduce:**
1. 
place Backpack pickup backpack 

**Expected behavior:**
Crash
**Screenshots (If applicable):**

**Additional information:**
Minecraft version: 1.12.2
Forge version: Forge  14.23.5.2847
Mod version: ImprovedBackpacks-1.12.2-1.4.0.0.jar

**Comment by socolio** [comment]
Crash can not be reproduced.
