### ISSUE TITLE
Toggle Chestplate Functionality [Config Option]

### ISSUE THREAD

**Issue by Brittank88** [DreenDex/ImprovedBackpacks-Issues#22]
**Your idea:**
A config option to remove the functionality of backpacks being used in the chestplate slot.

This prevents an issue where right clicking in the air with a backpack causes a hot-swap with an equipped chestplate, which is absolutely infuriating.

**Screenshots or art (if any):**
N/A

**Comment by socolio** [comment]
Can not be reproduced. Right clicking in the air causes open action.
