### ISSUE TITLE
Upgrade recipes can be crafted even if the backpack can't

### ISSUE THREAD

**Issue by nivthefox** [DreenDex/ImprovedBackpacks-Issues#24]
**Description:** When you have backpacks limited to a specific level (such as "Iron") by setting the `max_tier` option, the upgrade items for higher tier backpacks can still be crafted, resulting in wasted resources when people don't pay close attention to the limitations.

**To Reproduce:**
1. Configure `max_tier` to 3
2. Craft a diamond backpack upgrade.
3. Attempt to apply to an existing backpack.

**Expected behavior:**
You should not be able to craft upgrades which will never work.

**Screenshots (If applicable):**

**Additional information:**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Mod version: 1.4.1

**Comment by socolio** [comment]
Thanks for issue. This will be fixed in 1.4.2.0.
