### ISSUE TITLE
Hotkey doesn't open backpack in Baubles slot

### ISSUE THREAD

**Issue by marcmagus** [DreenDex/ImprovedBackpacks-Issues#3]
**Description:**

When a backpack from this mod is worn in the chest armor slot, the configured hotkey will open the backpack inventory. However, when it is worn in the baubles chest slot into which it fits, the hotkey does nothing.

I changed around the hotkeys to make sure there was no conflict on the key. It works properly in the armor slot.

**Expected behavior:**

Hotkey to work in baubles slot as in armor slot, or clear documentation that this doesn't work (in which case, why enable the baubles slot at all?)

**Additional information:**
Minecraft version: 1.12.2
Forge version: 14.23.3.2679
Mod version: 1.12.2-1.2.0.2
SevTech Ages version: 3.0.7 [In case there is a conflict I'm not seeing]

**Comment by DreenDex** [comment]
Fixed in 1.2.0.3
