### ISSUE TITLE
Hotkey opens backpack, but can't close it.

### ISSUE THREAD

**Issue by darchitectlp** [DreenDex/ImprovedBackpacks-Issues#30]
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Mod version: ImprovedBackpacks-1.12.2-1.5.0.0.jar

Hotkey opens backpack, but can't close it. Tried with the default "B" key and other keys. Backpack always opens, but I have to use my "Inventory" key or Escape to close out. Thanks!

**Comment by socolio** [comment]
Thnx for idea. But this feature will be added only in mod for mc 1.16.
1.12 version is legacy :(
