### ISSUE TITLE
Crash: Loading 'Improved Backpacks' + 'FancyMenu' and add New Element: PlayerEntity in Menu.

### ISSUE THREAD

**Issue by Shorepion** [DreenDex/ImprovedBackpacks-Issues#35]
## Environment
Minecraft version:  1.16.5
Forge version:  36.2.4
Mod version:  ImprovedBackpacks-1.6.0.0

## All active mods: 
-fancymenu_2.2.2-2_MC_1.16.2-1.16.5
-ImprovedBackpacks-1.6.0.0
-konkrete_1.1.6_MC_1.16.2-1.16.5

## Expected behaviour
> Should load the Customized Menu without crashing.

## Actual behaviour
> Crashing game to desktop

## Steps to reproduce
1. Create a Custom Menu in FancyMenu
2. Add "New Element">"Player Entitiy">"Auto name (will show the players skin/entity)

## Screenshots
> no screenshots

## CrashLog:
> https://pastebin.com/9rzmjACV

Already created an issue thread in FancyMenu GitHub:
https://github.com/Keksuccino/FancyMenu/issues/199

**Comment by socolio** [comment]
Thanks for your report! Fixed in 1.6.0.2.
