### ISSUE TITLE
Sewing Table Not Retrievable

### ISSUE THREAD

**Issue by CodexArchive** [DreenDex/ImprovedBackpacks-Issues#36]
## Environment
Minecraft version: 1.16.5
Forge version:  Forge 36.2.4
Mod version:  1.6.0.0

## Expected behavior
> Sewing table drops itself when broken

## Actual behavior
> When I attempt to break the sewing table to move it, it will drop all of the items in its inventory but the sewing table itself just disintegrates. Even if I use an axe with silk touch the table itself is not retrievable 

## Steps to reproduce
1. place sewing table
2. Break it
- No sewing table is dropped

**Comment by socolio** [comment]
I found all your broken sewing tables! There they are. They have flown far away...
![image](https://user-images.githubusercontent.com/14280202/133428574-17e7fd9c-290a-4621-ad55-7b84c8d21e9e.png)
(Thanks for your report! Fixed in 1.6.0.1)
