### ISSUE TITLE
Crash on world creation/join with Cold Sweat, others

### ISSUE THREAD

**Issue by enduum** [DreenDex/ImprovedBackpacks-Issues#37]
## Environment
Minecraft version:  1.16.5
Forge version:  36.2.0+
Mod version:  1.6.0.3

## Expected behaviour
Successful creation/joining of a world

## Actual behaviour
World creation: Load gets to 100% and then hangs indefinitely until force closed by the user. [[latest.log]](https://pastebin.com/Tuw4tbTa) [[crash report]](https://pastebin.com/zYJU2LSY)
World join: Game crashes. [[latest.log]](https://pastebin.com/CbtiVtUL) [[crash report]](https://pastebin.com/zGyhhas5)

## Steps to reproduce
1. Launch game
2. Create world
-Hang
or:
1. Launch game
2. Load existing world
-Crash

This has already been reported to the creators of Cold Sweat, this is their response:

![momoreply](https://user-images.githubusercontent.com/73849784/137986499-cfa6848c-ea32-46e0-a3bd-7708ae436874.png)

**Comment by socolio** [comment]
@enduum Does it happen randomly or every time?

**Comment by socolio** [comment]
Thx for your report! Problem was found in Cold Sweat. Issue and way to fix it reported to Mikul.

Protection against similar issues will be added in next (todays) update.
