### ISSUE TITLE
Server Crash - Ticking Player

### ISSUE THREAD

**Issue by FluxedU** [DreenDex/ImprovedBackpacks-Issues#38]
Game Crash when i try to Load/Create new World
[crash-2021-10-20_06.00.31-server.txt](https://github.com/DreenDex/ImprovedBackpacks-Issues/files/7383756/crash-2021-10-20_06.00.31-server.txt)

Version: 1.6.0.3
Game Version: 1.16.5

**Comment by socolio** [comment]
Thanks for your report! Problem with one of the installed mods. Looks like in forgery (fabrication). Someone failed with capability registration.

Protection agains this issues will be added in 1.6.1.0.
