### ISSUE TITLE
Duplication Glitch with Placed Backpacks

### ISSUE THREAD

**Issue by Drazuam** [DreenDex/ImprovedBackpacks-Issues#40]
## Environment
Minecraft version:  1.16.5
Forge version:  forge-1.16.5-36.2.20
Mod version:  ImprovedBackpacks-1.6.2.0

## Expected behaviour
> A placed backpack's GUI should disappear when the placed backpack is broken

## Actual behaviour
> When broken, the GUI for a placed backpack stays open.  This allows the player to take items from the "ghost" container and effectively duplicate items

## Steps to reproduce
1. Place backpack into world
2. Open backpack by right clicking it
3. While GUI is still open, break the backpack (another player, block breaking machine, etc)
4. Take items from the ghost container
5. See that the items are duplicated by opening the backpack item

**Comment by socolio** [comment]
Thanks for your report! We don't now how we missed this stupid glitch. Fixed in 1.6.2.1

**Comment by Drazuam** [comment]
Awesome, glad to see such a quick response time 👍
