### ISSUE TITLE
Can't Craft

### ISSUE THREAD

**Issue by SephElKal** [DreenDex/ImprovedBackpacks-Issues#47]
## Environment
Minecraft version:  1.16.5
Forge version:  36.2.20
Mod version:  1.3

## Expected behaviour
> Sewing Table should make Backpack

## Actual behaviour
> Sewing Table does not make a Backpack

## Steps to reproduce
1. Put all materials into Sewing Table
- Backpack doesn't show up in output

> Screenshots (If applicable)
![2023-05-17 13_39_04-Create_ Above and Beyond](https://github.com/DreenDex/ImprovedBackpacks-Issues/assets/133905565/556df0e9-a626-4751-be01-65524f9f12ce)

**Comment by socolio** [comment]
You need 5 tanned leather to craft backpack. Is it shows you in JEI that you need 1 tanned leather?
