### ISSUE TITLE
Place as block on death

### ISSUE THREAD

**Issue by naqaden** [DreenDex/ImprovedBackpacks-Issues#6]
Please consider an option to place worn backpacks as blocks on death. This could add some interesting value to backpacks, such as an extra layer of protection from explosions, fire, and fluids.

**Comment by Deliphin** [comment]
Wearable Backpacks does this, and it's a very nice feature if you don't have a death chest mod.

**Comment by naqaden** [comment]
Yeah! I originally started with Wearable Backpacks and loved that feature, but ultimately wanted Baubles compatibility as I personally found it awkward to wear backpacks in place of chest armor. IRL backpacks are worn over shirts and coats, though perhaps not over armor. I also run an armor set mod though, so chest pieces are extra valuable.

**Comment by DreenDex** [comment]
Sadly, we don't see Improved Backpacks as yet another "player grave" mod attempt or armor piece. It's too much different functionality from backpacks that we want.

We will not implement it in any version in the near future, but we want to thank you for your idea submission.
