### ISSUE TITLE
Ender Backpacks aren't by default blacklisted from going in backpacks

### ISSUE THREAD

**Issue by Deliphin** [DreenDex/ImprovedBackpacks-Issues#8]
**Description:** Ender backpacks can go inside other backpacks, while other backpacks cannot.

**To Reproduce:**
1. Take an ender backpack, and place it inside a normal backpack.

**Expected behavior:** Take an ender backpack, and try to place it in a normal backpack, it should not work.

**Screenshots (If applicable):** ![capture](https://user-images.githubusercontent.com/14265753/51138909-ca127600-1818-11e9-9a8d-51f6e5de5b8b.PNG)

**Additional information:**
Minecraft version: 1.12.2
Forge version: 2768
Mod version: 1.12.2-1.4.0.0

**Solution:** Add the following line to the default list for `S:blacklisted_items`:
`improvedbackpacks:ender_backpack`

And while you're at it, might want to add this to the blacklist too, it's not picked up by the oredict blacklist:
`wearablebackpacks:backpack`

**Comment by NotASocol** [comment]
In fact, Ender backpack is not a "backpack". It does not contain items. There's no point in adding it to the blacklist.

**Comment by Deliphin** [comment]
Uh, just because it doesn't store items itself doesn't mean it doesn't contain items. It's an immediate access to your ender chest. You have instant access to storage. It doesn't matter how it works internally, it matters how players will perceive it's likely use.

Plus more importantly, it would generally be intuitive that if you can't put in a normal backpack, a backpack that is externally identical would have the same restriction.

This causes confusion. Players who successfully placed an ender backpack in a normal backpack will question why they can't put a normal backpack in another normal backpack, and players who failed to put a normal backpack in a normal backpack won't even consider putting the ender backpack because it appears as the same thing, the only difference is it can magically connect to an ender chest instead of internal storage.

I'll put it to you this way: You have two cardboard boxes. They are both the same in appearance. One doesn't fit through your door, but the other does. Even though they're they look the same, they're the same size, same shape, but one just somehow fits while the other doesn't. Once you get inside, you see the one that fit has a portal to another dimension inside. But that didn't affect the dimensions or shape of the box. So even though it works differently inside, you're still confused as to why it fit when the other box didn't.

**Comment by NotASocol** [comment]
Ok, you are right. We'll add Ender Backpack to blacklist.
